import{a as b,i as m,S}from"./assets/vendor-CptLyL-E.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const O="52933898-64c235b98ac290495c49a4d77",q="https://pixabay.com/api/";async function p(e,t=1){const s={key:O,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t},a=await b.get(q,{params:s});return{images:a.data.hits,totalHits:a.data.totalHits}}function g(e){return e.map(({webformatURL:t,largeImageURL:s,tags:a,likes:r,views:o,comments:i,downloads:w})=>`
      <li class="card">
        <a href="${s}" target="_blank" rel="noopener noreferrer">
          <img src="${t}" alt="${a}" loading="lazy" />
        </a>
        <div class="stats">
          <div><span>Likes</span>${r}</div>
          <div><span>Views</span>${o}</div>
          <div><span>Comments</span>${i}</div>
          <div><span>Downloads</span>${w}</div>
        </div>
      </li>`).join("")}function I(){document.querySelector(".gallery").innerHTML=""}function h(e,t=!1){const s=document.querySelector(".gallery");t?s.insertAdjacentHTML("beforeend",e):s.innerHTML=e}const v=e=>m.show({class:"custom-error-toast",timeout:4e3,close:!0,overlay:!1,position:"topRight",title:"",message:e,progressBar:!1,transitionIn:"fadeInDown",transitionOut:"fadeOutUp",closeOnClick:!0}),u=e=>m.show({class:"custom-info-toast",timeout:3e3,close:!0,overlay:!1,position:"topRight",title:"",message:e,progressBar:!1,transitionIn:"fadeInDown",transitionOut:"fadeOutUp",closeOnClick:!0}),H=document.querySelector(".form"),d=document.querySelector(".loader");document.querySelector(".gallery");const n=document.querySelector(".load-more");let L=new S(".gallery a",{captionsData:"alt",captionDelay:250}),f=1,c="",y=0,l=0;H.addEventListener("submit",A);n.addEventListener("click",M);async function A(e){if(e.preventDefault(),c=e.target.elements.search.value.trim(),!c){u("Please, enter a search query!");return}I(),f=1,l=0,d.classList.add("active"),n.style.display="none";try{const{images:t,totalHits:s}=await p(c,f);if(t.length===0){u("Sorry, there are no images matching your search query.");return}y=s,l=t.length,h(g(t)),L.refresh(),l<y&&(n.style.display="block")}catch(t){console.error(t),v("An error occurred while fetching images.")}finally{d.classList.remove("active")}}async function M(){f+=1,d.classList.add("active"),n.style.display="none";try{const{images:e}=await p(c,f);if(e.length===0){u("No more images.");return}l+=e.length,h(g(e),!0),L.refresh(),P(),l>=y?(u("We're sorry, but you've reached the end of search results."),n.style.display="none"):n.style.display="block"}catch{v("An error occurred while fetching images.")}finally{d.classList.remove("active")}}function P(){const e=document.querySelectorAll(".gallery .card");if(e.length>0){const t=e[0].getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
